image: WMF 5

version: 0.1.{build}

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /update(?:|d|s) readme\..*/

environment:
  PSGalleryApiKey:
    secure: 19uAs7mfu9YRkwTvHIymJuSyXGjUUXCR+jsaRvo3ST44NmgZG2HZkOjuabTe/Cyu
  CODECOV_TOKEN:
    secure: PDm+SISN88zXCVjo/8ULJMC+kg2plOEnYGi9fDgY2IcE/NiZTxwrUspqI9CIIRrM



install:
# Bootstrap PSDepend and Install Dependencies
- ps: |
    Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force
    Install-Module -Name PSDepend -Force; Import-Module -Name PSDepend
    Invoke-PSDepend '.\REQUIREMENTS.psd1' -Force



build_script:
- ps: Invoke-psake '.\.scripts\build.ps1' -Properties @{'SkipBootStrap' = $true}



on_success:
# If build was started by pushed tag; deploy it.
- ps: |
    Write-Host "[AppVeyor] On Success; deploying ..." -Foregroundcolor Green
    Invoke-PSDeploy -Path '.\.scripts\deploy.ps1' -Force