image: WMF 5

version: 0.3.{build}

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /update(?:|d|s) readme\..*/

environment:
  PSGalleryApiKey:
    secure: 19uAs7mfu9YRkwTvHIymJuSyXGjUUXCR+jsaRvo3ST44NmgZG2HZkOjuabTe/Cyu
  CODECOV_TOKEN:
    secure: 



install:
# Bootstrap PSDepend and Install Dependencies
- ps: |
    Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force
    Install-Module -Name PSDepend -Force; Import-Module -Name PSDepend
    Invoke-PSDepend '.\REQUIREMENTS.psd1' -Force



build_script:
- ps: Invoke-psake '.\.scripts\build.ps1' -Properties @{'SkipBootStrap' = $true}



# deploy:
#   release: v$(APPVEYOR_BUILD_VERSION)
#   description: ePOwerShell v$(appveyor_build_version)
#   provider: GitHub
#   auth_token:
#     secure: EHLdOgH35OJQ/AAj6dXn/iQ9datyBKgai5JGB+Lbh9Yaltk4wLefi2MIfGZ5N2ca
#   artifact: /.*\.zip/
#   draft: false
#   prerelease: true
#   on:
#     branch: master                 # release from master branch only
#     appveyor_repo_tag: false        # deploy except on tag push only



on_success:
# If build was started by pushed tag; deploy it.
- ps: |
    Write-Host "[AppVeyor] On Success; deploying ..." -Foregroundcolor Green
    Invoke-PSDeploy -Path '.\.scripts\deploy.ps1' -Force